services:

    ajir_contact.form:
        class: Symfony\Component\Form\Form
#        arguments: ['@ajir_contact.form.type']
        arguments: ['Ajir\ContactBundle\Form\ContactType']
        factory: ["@form.factory", create]

    ajir_contact.form.type:
        class: Ajir\ContactBundle\Form\ContactType
        tags:
            - { name: form.type }

    ajir_contact.form.handler:
        class: Ajir\ContactBundle\Form\ContactHandler
        scope: request
        arguments: 
            - '@ajir_contact.form'
            - '@ajir_contact.service.mailer'

    ajir_contact.service.mailer:
        class: Ajir\ContactBundle\Service\Mailer
        arguments:
            - '@mailer'

    ajir_contact.controller:
        class: Ajir\ContactBundle\Controller\ContactController
        arguments:
            - '@templating'
            - '@session'
            - '@translator'
            - '@ajir_contact.form.handler'
